Rename to LUSCA_HEAD

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,11 +1,11 @@
 dnl
-dnl  Configuration input file for Squid
+dnl  Configuration input file for Lusca
 dnl
-dnl  $Id$
+dnl  $Id: configure.in 12542 2008-04-13 13:27:23Z adrian.chadd $
 dnl
 dnl
 dnl
-AC_INIT(Squid Web Proxy, 2.HEAD-CVS, http://www.squid-cache.org/bugs/, squid)
+AC_INIT(Lusca Web Proxy, LUSCA_HEAD, http://www.cacheboy.net/, Lusca)
 AC_PREREQ(2.52)
 AM_CONFIG_HEADER(include/autoconf.h)
 AC_CONFIG_AUX_DIR(cfgaux)
@@ -944,6 +944,22 @@ AC_ARG_ENABLE(devpoll,
   esac
 ])
 
+dnl Enable Solaris Event Ports
+AC_ARG_ENABLE(eventports,
+[  --enable-eventports    Use Solaris event ports instead of poll],
+[
+  case "$enableval" in
+  yes)
+    echo "Forcing eventports to be enabled"
+    SELECT_TYPE="eventports"
+    ;;
+  no)
+    echo "Forcing eventports to be disabled"
+    ;;
+  esac
+])
+
+
 
 dnl Disable HTTP violations
 HTTP_VIOLATIONS=1
@@ -1124,18 +1140,44 @@ dnl "-64" from LDFLAGS
 	;;
 esac
 
-dnl Enable Linux transparent proxy support
+dnl Enable Linux transparent proxy support v2
 AC_ARG_ENABLE(linux-tproxy,
 [  --enable-linux-tproxy
-			  Enable real Transparent Proxy support for Netfilter TPROXY.],
+			  Enable real Transparent Proxy support for Netfilter TPROXY v2.],
 [ if test "$enableval" = "yes" ; then
 	echo "Linux Netfilter/TPROXY enabled"
-	AC_DEFINE(LINUX_TPROXY, 1, [Enable real Transparent Proxy support for Netfilter TPROXY.])
+	AC_DEFINE(LINUX_TPROXY, 1, [Enable real Transparent Proxy support for Netfilter TPROXY v2.])
 	LINUX_TPROXY="yes"
         if test -z "$LINUX_NETFILTER"; then
 	    echo "Linux-Netfilter Transparent Proxy automatically enabled"
 	    LINUX_NETFILTER="yes"
 	fi
+  fi
+])
+
+dnl Enable Linux transparent proxy v4 support
+AC_ARG_ENABLE(linux-tproxy4,
+[  --enable-linux-tproxy4
+			  Enable real Transparent Proxy support for Netfilter TPROXY v4.],
+[ if test "$enableval" = "yes" ; then
+	echo "Linux Netfilter/TPROXY v4 enabled"
+	AC_DEFINE(LINUX_TPROXY4, 1, [Enable real Transparent Proxy support for Netfilter TPROXY v4.])
+	LINUX_TPROXY4="yes"
+        if test -z "$LINUX_NETFILTER"; then
+	    echo "Linux-Netfilter Transparent Proxy automatically enabled"
+	    LINUX_NETFILTER="yes"
+	fi
+  fi
+])
+
+dnl Enable FreeBSD tproxy-like support
+AC_ARG_ENABLE(freebsd-tproxy,
+[  --enable-freebsd-tproxy
+			  Enable IP source-address spoofing with FreeBSD.],
+[ if test "$enableval" = "yes" ; then
+	echo "FreeBSD IP_NONLOCALOK enabled"
+	AC_DEFINE(FREEBSD_TPROXY, 1, [Enable IP source-address spoofing with FreeBSD.])
+	FREEBSD_TPROXY="yes"
   fi
 ])
 
@@ -1569,10 +1611,17 @@ AC_PATH_PROG(LN, ln, cp)
 AC_PATH_PROG(PERL, perl, none)
 dnl automake handles this AC_PATH_PROG(MAKEDEPEND, makedepend, $TRUE)
 AC_PATH_PROG(AR, ar, $FALSE)
+AC_CHECK_PROG(uudecode, uudecode$EXEEXT, yes)
 
 if test "$ac_cv_path_PERL" = "none"; then
 	echo "Perl is required to compile Squid"
 	echo "Please install Perl and then re-run configure"
+	exit 1
+fi
+
+if test "$ac_cv_prog_uudecode" != "yes"; then
+	echo "uudecode is required to compile Squid"
+	echo "Please install uudecode and then re-run configure"
 	exit 1
 fi
 
@@ -2482,7 +2531,7 @@ AM_CONDITIONAL([USE_SELECT_SIMPLE], [test $SELECT_TYPE = select_simple])
 AM_CONDITIONAL([USE_SELECT_WIN32], [test $SELECT_TYPE = select_win32])
 AM_CONDITIONAL([USE_KQUEUE], [test $SELECT_TYPE = kqueue])
 AM_CONDITIONAL([USE_DEVPOLL], [test $SELECT_TYPE = devpoll])
-
+AM_CONDITIONAL([USE_EVENTPORTS], [test $SELECT_TYPE = eventports])
 
 dnl Hmm.. some OS:es (i.e. FreeBSD) can't handle large AF_UNIX dgram packets.
 dnl Verify that at least 16K is supported, if not fall back on using
@@ -2582,16 +2631,6 @@ if test "$ac_cv_func_setresuid" = "yes" ; then
   AC_DEFINE(HAVE_SETRESUID, 1, [Yay! Another Linux brokenness.  Its not good enough to know that
 	setresuid() exists, because RedHat 5.0 declare setresuid() but
 	doesn't implement it.])
-fi
-
-AM_CONDITIONAL(NEED_OWN_SNPRINTF, false)
-if test "$ac_cv_func_snprintf" = "no" || test "$ac_cv_func_vsnprintf" = "no" ; then
-  AM_CONDITIONAL(NEED_OWN_SNPRINTF, true)
-fi
-
-AM_CONDITIONAL(NEED_OWN_STRSEP, false)
-if test "$ac_cv_func_strsep" = "no" ; then
-  AM_CONDITIONAL(NEED_OWN_STRSEP, true)
 fi
 
 dnl
@@ -3277,6 +3316,22 @@ dnl done
 
 AC_OUTPUT([\
 	Makefile \
+	app/Makefile \
+	app/tcptest/Makefile \
+	libmime/Makefile \
+	libsqdns/Makefile \
+	libsqident/Makefile \
+	libsqinet/Makefile \
+	libhelper/Makefile \
+	libhttp/Makefile \
+	libiapp/Makefile \
+	libstat/Makefile \
+	libcore/Makefile \
+	libsqdebug/Makefile \
+	libmem/Makefile \
+	libcb/Makefile \
+	libsqname/Makefile \
+	libstmem/Makefile \
 	lib/Makefile \
 	scripts/Makefile \
 	scripts/RunCache \
