This commit was manufactured by cvs2svn to create tag 'SQUID_2_5_STABLE11_RC1'.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -9,7 +9,7 @@ dnl
 dnl
 AC_INIT(src/main.c)
 AC_CONFIG_AUX_DIR(cfgaux)
-AM_INIT_AUTOMAKE(squid, 2.5.STABLE10-CVS)
+AM_INIT_AUTOMAKE(squid, 2.5.STABLE11-RC1-CVS)
 AM_CONFIG_HEADER(include/autoconf.h)
 AC_REVISION($Revision$)dnl
 AC_PREFIX_DEFAULT(/usr/local/squid)
@@ -21,6 +21,7 @@ if test -z "$LDFLAGS"; then
 fi
 
 PRESET_CFLAGS="$CFLAGS"
+PRESET_LDFLAGS="$LDFLAGS"
 
 dnl Check for GNU cc
 AC_PROG_CC
@@ -786,16 +787,13 @@ AC_ARG_WITH(build-environment,
                           XBS5_LP64_OFF64        64 bits (legacy)
                           XBS5_LPBIG_OFFBIG      large pointers and files (legacy)
                           default                The default for your OS],
-[ case "$enableval" in
+[ case "$withval" in
   yes|no)
 	echo "--with-build-environment expects a build environment string as used by getconf"
 	exit 1
 	;;
-  _*)
-	buildmodel="$enableval"
-	;;
   *)
-	buildmodel="_$enableval"
+	buildmodel="$withval"
 	;;
   esac
 ])
@@ -813,11 +811,33 @@ if test $needlargefiles && test -z "$buildmodel"; then
 		CFLAGS="-D_FILE_OFFSET_BITS=64 $CFLAGS"
 	fi
 fi
-if test -n "$buildmodel" && test "$buildmodel" != "_default"; then
+if test -n "$buildmodel" && test "$buildmodel" != "default"; then
 	echo "Using $buildmodel build environment"
+	if test "`getconf _$buildmodel 2>/dev/null || true`" = 1 || test "`getconf $buildmodel 2>/dev/null || true`" ; then
+	    : # All fine
+	else
+	    echo "ERROR: Build environment $buildmodel not known to getconf."
+	    exit 1
+	fi
 	CFLAGS="`getconf ${buildmodel}_CFLAGS` $CFLAGS"
 	LIBS="`getconf ${buildmodel}_LIBS` $LIBS"
 	LDFLAGS="`getconf ${buildmodel}_LDFLAGS` $LDFLAGS"
+dnl
+dnl On Solaris getconf returns for CFLAGS -Xa and -Usun options, but:
+dnl   -Xa is supported only by Sun cc, so we need to remove it when using gcc
+dnl   The 'sun' define is needed by ipfilter includes, so we must remove -Usun
+	case "$host" in
+	    *-solaris*)
+    		if test "$GCC" = "yes"; then
+		    echo "Removing -Xa for gcc on $host"
+		    CFLAGS="`echo $CFLAGS | sed -e 's/-Xa//'`"
+		fi
+   	        echo "Removing -Usun for gcc on $host"
+		CFLAGS="`echo $CFLAGS | sed -e 's/-Usun//'`"
+		;;
+	    *)
+	        ;;
+	esac
 fi
 
 AM_CONDITIONAL(MAKE_LEAKFINDER, false)
@@ -1317,6 +1337,7 @@ AC_CHECK_HEADERS( \
 	sys/mount.h \
 	sys/msg.h \
 	sys/param.h \
+	sys/prctl.h \
 	sys/resource.h \
 	sys/select.h\
 	sys/socket.h \
@@ -1794,6 +1815,7 @@ AC_CHECK_FUNCS(\
 	mktime \
 	mstats \
 	poll \
+	prctl \
 	pthread_attr_setscope \
 	pthread_setschedparam \
 	pthread_attr_setschedparam \
@@ -1930,6 +1952,17 @@ if test "$IPF_TRANSPARENT" = "no" ; then
     echo "WARNING: Cannot find necessary IP-Filter header files"
     echo "         Transparent Proxy support WILL NOT be enabled"
     sleep 10
+elif test "$IPF_TRANSPARENT" = "yes" ; then
+dnl On Solaris Ipfilter includes expect that SOLARIS2 is defined with the
+dnl Solaris minor version (8, 9, 10, ...)
+    case "$host" in
+	*-solaris*)
+	    solrev=`uname -r | sh -c 'IFS=. read j n x; echo $n'`
+	    CFLAGS="-DSOLARIS2=$solrev $CFLAGS" 
+	    ;;
+	*)
+	    ;;
+     esac
 fi
 
 dnl PF support requires a header file.
